### ISSUE TITLE
关于编码问题想请教一下

### ISSUE THREAD

**Issue by brainchen2020** [SkyTNT/midi-model#11]
关于编码问题请教一下，能不能把现有的midi多轨道同时编码(多个轨道同时编码)，变成一轨完成再接着另一轨，一轨只有一个乐器，
比如: 
   编完完整的钢琴轨后，在钢琴轨后面继续编吉他或者其他乐器，再重复这样。
（解码时再同步各个乐器），
我觉得这样做的好处是容易单独调整单声部。
或许容易根据钢琴续写🎸或者鼓组或者其它。
或者根据旋律续写和声。
我感觉拓展性强，估计实现比较复杂。（我还没时间仔细研究Tokenizer）
不知道这样实现是否可行？

**Comment by SkyTNT** [comment]
不太行，midi序列是时间序列，每个轨道只能同时生成，不能先生成一轨再生成另一轨。

**Comment by brainchen2020** [comment]
受DAW midi 编辑器启发，它们可以单独编辑(/录制)每一轨的音符?，我觉得按道理应该有点希望，可能编码方式不一样。

**Comment by brainchen2020** [comment]
现在轨道之间的音符🎵是相对时间嘛？如果转成绝对时间能不能分开？

**Comment by SkyTNT** [comment]
不是改什么时间的问题,是改模型的问题,我没时间研究,你自己研究吧

**Comment by brainchen2020** [comment]
了解，我再看看怎么弄。

**Comment by SkyTNT** [comment]
可以看看#5

**Comment by brainchen2020** [comment]
嗯嗯好哒
