### ISSUE TITLE
Fine tuning notebook

### ISSUE THREAD

**Issue by Sebastian-Ballesteros** [SkyTNT/midi-model#12]
First of all, thank you for creating the model. It's an exemplary and straightforward implementation. 

I'm working on a university project where we want to do a style transfer for music generation. Please help us by providing a notebook with the code necessary for fine-tuning or pointing me in the right direction. I'm new to the field and struggling a bit with navigating your code. 

Thank you so much for your help

**Comment by SkyTNT** [comment]
Maybe you can take a look at this #7
