### ISSUE TITLE
[Sugguestion] Add the selector for the other models that are available for the app-gpu version

### ISSUE THREAD

**Issue by RustyKit-JohnW** [SkyTNT/midi-model#19]
Seems like the other models would be cool to have for the windows gpu app version since i notice its only a thing on the colab/hugging face version and both are super slow compared to my gpu i have locally (colab/hugging face ~7 it/s) where as local machine is around 20-29 it/s story short is the other models would be cool to have locally

**Comment by SkyTNT** [comment]
Updated version will be released later
