### ISSUE TITLE
How to install and use Fluidsynth?

### ISSUE THREAD

**Issue by pbz134** [SkyTNT/midi-model#26]
Hello,

I cloned the repo and installed all the dependencies. Apparently, pip installed Fluidsynth 0.2, which is lower than 2.0 as written in your repo (obviously).

When running, I get the following error:
Traceback (most recent call last):
  File "D:\PythonTests\midi-model\app.py", line 371, in <module>
    synthesizer = MidiSynthesizer(soundfont_path)
  File "D:\PythonTests\midi-model\midi_synthesizer.py", line 11, in __init__
    fl = fluidsynth.Synth(samplerate=float(sample_rate))
AttributeError: module 'fluidsynth' has no attribute 'Synth'

I also saw that you linked the official fluidsynth website, so I downloaded it and added the .exe directory to PATH. However, it didn't change anything.

**Comment by pbz134** [comment]
Sorry, nevermind! I forgot to restart the terminal. It works fine now :)

**Comment by Sakura-Hydrangea** [comment]
guy，how to solve this problem，i also meet the same bug

**Comment by Sakura-Hydrangea** [comment]
<img width="615" alt="image" src="https://github.com/user-attachments/assets/7be092d5-a927-4da6-a76f-a5997f05744b">
i also download fluid and add it to PATH, but still error

**Comment by Sakura-Hydrangea** [comment]
ok fine i have solved it
