### ISSUE TITLE
ValueError:  `val_check_interval` (1600) must be less than or equal to the number of the training batches (30)

### ISSUE THREAD

**Issue by pbz134** [SkyTNT/midi-model#27]
Hello,

I am currently trying to train a model on 160 midi files with this command:
python train.py --task train --data dataset_DJSH --data-val-split 100 --lr 2e-4 --warmup-step 100 --max-step 1000 --accelerator gpu

And this is the error I am getting:
ValueError:  `val_check_interval` (1600) must be less than or equal to the number of the training batches (30). If you want to disable validation set `limit_val_batches` to 0.0 instead. If you want to validate based on the total training batches, set `check_val_every_n_epoch=None`

And help on how I could fix this?
Thanks!

**Comment by SkyTNT** [comment]
--val-step 0

**Comment by pbz134** [comment]
Thanks! That seemed to have solved it.
One more thing though - Since the normal train task gave me bad results after 30 epochs (might be the dataset or something else), I wanted to try to train a lora file.

This is my command:
python train.py --task lora --data dataset_DJSH --data-val-split 100 --lr 2e-4 --warmup-step 100 --max-step 1000 --accelerator gpu --val-step 0 --ckpt default/model_base.onnx

No matter how I specify the ckpt, it either says "permission denied" with "--ckpt default" or gives me an invalid load key error with "--ckpt default/model_base.onnx"
(The model is copied from your .exe release of the program)

I would appreciate your help!

**Comment by SkyTNT** [comment]
You need to specify the pytorch model file instead of onnx. https://huggingface.co/skytnt/midi-model-tv2o-medium/blob/main/pytorch_model.bin

**Comment by pbz134** [comment]
Ah perfect. It's running fine now :)

**Comment by pbz134** [comment]
@SkyTNT Sorry if I'm bothering you or anything, but may I know the training parameters you used for the Touhou Lora (or the command)?
I tried to train my own for ~30 epochs on the 200 midi files but the result was really bad. The model's output just consisted of garbage.

**Comment by SkyTNT** [comment]
You shouldn't use --data-val-split 100. If you only have 160 midi files, then only 60 midi files will be used for training. You should use --data-val-split 8

**Comment by SkyTNT** [comment]
How did you load the model? To load a lora, you need to first load the base model that trains the lora before loading the lora. And the lora needs to use the file saved in a dedicated folder. Do not use .ckpt generated from training.

**Comment by pbz134** [comment]
Hey @SkyTNT sorry to keep you waiting. I am not at my PC and this is what I get when loading the original model with a trained lora:
![grafik](https://github.com/user-attachments/assets/4574e43f-6eeb-47ee-8e0e-7b1ba076df2c)
