### ISSUE TITLE
在 '__init__.py' 中找不到引用 'Synth' 

### ISSUE THREAD

**Issue by Sakura-Hydrangea** [SkyTNT/midi-model#28]
<img width="548" alt="image" src="https://github.com/user-attachments/assets/e747c478-9a32-4814-ae01-b6e2e1d523ad">
这里有bug

**Comment by SkyTNT** [comment]
这只是你IDE的问题，我是可以显示的。
![image](https://github.com/user-attachments/assets/57a36962-bb29-4b01-a148-66ef85389e14)
