### ISSUE TITLE
想请教一下为什么我在使用app.py时有异常

### ISSUE THREAD

**Issue by liukkcggvb** [SkyTNT/midi-model#30]
<img width="1177" alt="屏幕截图 2024-11-27 201809" src="https://github.com/user-attachments/assets/2f075f23-dcb2-4d99-a927-c59a0bc180c0">
你好，我在linux上部署了模型，在我使用app.py的时候，尝试过加载safetensors模型和bin模型，但是效果如上图所示，非常混乱。请问怎么解决？
我只修改了以下获得加载模型路径的代码，点击加载时页面也显示“success”。
def get_model_path():
    ckpt_files = glob.glob("../*/*.ckpt", recursive=True)
    bin_files = glob.glob("../*/*.bin", recursive=True)
    safetensors_files = glob.glob("../*/*.safetensors", recursive=True) #/home/qpliu/midi/midi-model-tv2o-medium/model.safetensors
    model_paths = sorted(ckpt_files + bin_files + safetensors_files)
    model_paths = [model_path for model_path in model_paths if "adapter_model" not in model_path]  # lora
    return gr.Dropdown(choices=model_paths)

**Comment by liukkcggvb** [comment]
Should I use "onnx" models?

**Comment by SkyTNT** [comment]
请提供你具体的加载步骤

**Comment by liukkcggvb** [comment]
感谢回复，我试了一下在windows系统下部署是没有问题的，在linux下有问题，但部署的方式和windows基本一样（除了安装fluidsynth包的方式）。我以后在windows下使用就好了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月1日(周日) 下午3:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SkyTNT/midi-model] 想请教一下为什么我在使用app.py时有异常 (Issue #30)




 
请提供你具体的加载步骤
