### ISSUE TITLE
long-term composition

### ISSUE THREAD

**Issue by AlexanderMolina** [SkyTNT/midi-model#31]
I can't find a way to continue a composition. I would like to be able to continue from a complete midi, not just 512 midi events.
![image](https://github.com/user-attachments/assets/4324a389-d0ae-4e43-b88d-231a9ce2e2a1)

**Comment by SkyTNT** [comment]
Maybe I could set the max value to 4096 or something?

**Comment by AlexanderMolina** [comment]
An even larger number.
Is it possible to create a symphony?

**Comment by SkyTNT** [comment]
Yes, it can make symphonies, but most of the time the result is not good. Because most symphonies have dense notes.

**Comment by AlexanderMolina** [comment]
I prefer to be able to compose without limits, I am also aware that my PC hardware is a limit.
