### ISSUE TITLE
Convert Pytorch Lightning model to Huggingface model issues

### ISSUE THREAD

**Issue by brainchen2020** [SkyTNT/midi-model#4]
你好，感谢你的开源这个项目。

我目的想把扩大”max seq length“到8192，由于我的GPU只有20G的限制，考虑到之前使用过HF的QLora-For-Llama推理大模型的经验。
我想把PL的模型转成HF模型，再使用QLora量化来减少VRAM。

我尝试了一个下午好像把模型转过去了，但是Tokenizer无从下手（没有找到好的参考模式）。
模型的训练方式也要改。（我对HF底层原理不是很熟悉）
参考 https://huggingface.co/docs/transformers/custom_models#writing-a-custom-model

想请教一下有转HF模型的想法吗？
谢谢！

Hello, thanks for open source this project.

My intention was to expand the "max seq length" to 8192, since my GPU is only limited to 20G, given my previous experience using HF's QLora-For-Llama inference large model.
I want to convert the PL model to the HF model and use QLora quantization to reduce VRAM.

I tried for an afternoon and seemed to turn the model around, but Tokenizer couldn't get started (didn't find a good reference pattern).
The training method of the model should also be changed. (I'm not very familiar with the underlying principle of HF)
Refer to https://huggingface.co/docs/transformers/custom_models#writing-a-custom-model

Do you have an idea of switching to the HF model?
Thank you!

**Comment by SkyTNT** [comment]
我这模型本身就是两个hf transformers中的LlamaModel组成的，你可以试试直接在这两个LlamaModel上进行操作
https://github.com/SkyTNT/midi-model/blob/99b79d5c1eb22014df22f4178d6b86ddec0f55ab/midi_model.py#L17-L24

整体兼容hf transformers感觉好像不太行，所以我不打算整体转成hf transformers模型

**Comment by brainchen2020** [comment]
嗯嗯，我试试
这个MIDI模型是我目前见过的效果最好的模型！

**Comment by SkyTNT** [comment]
一个月

**Comment by brainchen2020** [comment]
我关了
