### ISSUE TITLE
Thank you again! :)

### ISSUE THREAD

**Issue by asigalov61** [SkyTNT/midi-model#6]
Hey @SkyTNT 

I just wanted to thank you again for your great work/code! :)

Please check out my project which is based on your code/implementation and on one of my models:
https://huggingface.co/spaces/asigalov61/Allegro-Music-Transformer

This project was only possible thanks to you and your code :)

Thank you and I would love to hear any thoughts or feedback from you :)

Sincerely,

Alex.

**Comment by SkyTNT** [comment]
You’re welcome. 
I'm glad you used my code for your project.
It looks pretty good. It would be even better if I could use my latest javascript implementation of MidiVisualizer. I saw you modified the default patch in midi_synthesizer.py, I think this is not good, it should ensure generality and not be project-specific.

**Comment by asigalov61** [comment]
@SkyTNT Thank you for your feedback! :)

You are absolutely right about midi_synthesizer.py! I will correct it to determine midi patches automatically from the input score seq.

I actually wanted to use your MIDI visualizer but I am absolutely horrible with Javascript and OOP, so I had to go with what I could implement. :(

Have you been able to make onnxruntime to work on CPUs? I am getting an error if I use CPUExecutionProvider alone.

Alex.

**Comment by SkyTNT** [comment]
> Have you been able to make onnxruntime to work on CPUs? I am getting an error if I use CPUExecutionProvider alone.

What error did you get?

**Comment by asigalov61** [comment]
@SkyTNT I get onnxruntime error 9 about the Tril not being implemented in version (14) of ops I am using.

It happens if I use CPUExecutionProvider as a provider for onnxruntime init. When I use both (CPU+GPU) everything works fine.
I am assuming it is because there is some kind of problem with my onnx model/graph. Maybe it did not convert properly.

But it is ok. I switched my Hugging Face Spaces implementation to PyTorch. Now it works fine on CPU and it is easier for me anyway.

I wanted to ask you something though... Can you help me adapt your MIDI Visualizer code to my implementation/MIDI encoding?

**Comment by SkyTNT** [comment]
> @SkyTNT I get onnxruntime error 9 about the Tril not being implemented in version (14) of ops I am using.

Maybe it’s related to https://github.com/microsoft/onnxruntime/issues/9494

> I wanted to ask you something though... Can you help me adapt your MIDI Visualizer code to my implementation/MIDI encoding?

Sure, I'll try it.

**Comment by asigalov61** [comment]
> > @SkyTNT I get onnxruntime error 9 about the Tril not being implemented in version (14) of ops I am using.
> 
> Maybe it’s related to [microsoft/onnxruntime#9494](https://github.com/microsoft/onnxruntime/issues/9494)
> 

Yes, but I searched the internet pretty extensivelly and there does not appear to be a solution for this problem with onnxruntime atm :(


> > I wanted to ask you something though... Can you help me adapt your MIDI Visualizer code to my implementation/MIDI encoding?
> 
> Sure, I'll try it.

Thank you so much. I will really appreciate it. Please let me know at your convenience if you are able to do it so that I can try to integrate it.

Alex

**Comment by SkyTNT** [comment]
@asigalov61 I finished it.
[Allegro-Music-Transformer.zip](https://github.com/SkyTNT/midi-model/files/12615496/Allegro-Music-Transformer.zip)

**Comment by asigalov61** [comment]
@SkyTNT Thank you so much :) I will try it right now and report the results shortly :)

**Comment by asigalov61** [comment]
@SkyTNT Yes!!! It works flawlessly!!! :) Thank you so much!!! You have mad skills!!! :)

I have a question though...Is it possible to make visualizer canvas size dynamic based on requested number of tokens? My implementation is set to generate 256 tokens by default (~70 notes) so the canvas (on PC screen) looks way too big and on the phone screen it looks way too small. Is it possible to make it dynamic?

Alex.

**Comment by SkyTNT** [comment]
@asigalov61 You can add this code to adapt your screen size.

```js
    if(window.innerWidth < 300){ 
        midi_visualizer.config.noteHeight = 1
        midi_visualizer.config.beatWidth = 8
    }else if(window.innerWidth < 600){
        midi_visualizer.config.noteHeight = 2
        midi_visualizer.config.beatWidth = 16
    }else if(window.innerWidth < 1280){
        midi_visualizer.config.noteHeight = 4
        midi_visualizer.config.beatWidth = 32
    }else {
        midi_visualizer.config.noteHeight = 4
        midi_visualizer.config.beatWidth = 64
    }
    midi_visualizer.svg.style.height = `${midi_visualizer.config.noteHeight*128}px`; //reload svg height
```

Add the code after this line

https://github.com/SkyTNT/midi-model/blob/745c6f49085a42e800ee240c884166e55f4dc73e/javascript/app.js#L313

**Comment by asigalov61** [comment]
@SkyTNT Thank you so much for your help! This works great! :)

If you will ever need my help with your music project(s), please do not hesitate to reach out to me. I would be very glad to help you with what I can :)

Most sincerely,

Alex

**Comment by asigalov61** [comment]
@SkyTNT P.S. I gave you credit for your great code on my project GitHub.

Thanks again :)
